name: easistent_timetable
description: eAsistent timetable parser
version: 0.0.1
author: Gašper Dobrovoljc
homepage: https://github.com/gapidobri/easistent_timetable

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_scraper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: